name: "Deploy Infraestructura Base"

on:
  push:
    branches: [main, develop, qa, predevelop]
    paths:
      - "infra/**.tf"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform Apply Infra Base"
    runs-on: ubuntu-latest
    environment: AWS

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Set environment name
        id: set-env
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "environment=prod" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
            echo "environment=dev" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF_NAME}" == "qa" ]]; then
            echo "environment=qa" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF_NAME}" == "predevelop" ]]; then
            echo "environment=predev" >> "$GITHUB_OUTPUT"
          else
            echo "environment=unknown" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Inicializar Terraform
        run: terraform init
        env:
          TF_VAR_region: us-east-1
          TF_VAR_environment: ${{ steps.set-env.outputs.environment }}
          AWS_REGION: us-east-1
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Validar sintaxis
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan -out=tfplan

      - name: Aplicar Terraform
        run: terraform apply -auto-approve tfplan

      - name: Output
        run: terraform output
